# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Artamoshkin Maxim
email: admin@zverit.com
description: > # this means to ignore newlines until "baseurl:"
  Добро пожаловать на блог разработчика. 
  
  Здесь я пишу в основном о веб-разработке, в частности
  о ASP.NET, С<span>#</span>, JavaScript. А также пишу об околокодинговых темах. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.zverit.com" # the base hostname & protocol for your site
twitter_username: zverit 
github_username:  Zverit

safe: true

gems:
  - jekyll-sitemap
   
# Build settings   
markdown: kramdown

url: https://blog.zverit.com   # with the https protocol
enforce_ssl: blog.zverit.com   # without any protocol
